<!-- <div class="addthis_toolbox addthis_default_style">
    <span class="addthis_separator"> </span>
    <a class="addthis_button_facebook_like"></a>
    <a class="addthis_button_wykop"></a>
    <a class="addthis_button_facebook"></a>
    <a class="addthis_button_twitter"></a>
    <a class="addthis_button_blip"></a>    
    <span class="addthis_separator"> </span>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=hhbd"></script> -->