<li class="elem">
  <a class="cover" href="<?php echo $this->url(array('id' => $this->album->id, 'seo' => $this->album->artist->url . ' - ' . $this->album->url), 'album'); ?>">
    <img src="<?php echo $this->album->thumbnail; ?>" alt="Okładka <?php echo $this->album->artist->name . ' - ' . $this->album->title; ?>" title="<?php echo $this->album->artist->name . ' - ' . $this->album->title; ?>"/>
    <span></span>
  </a>
  <ul class="info">
    <li>
        <?php echo $this->partial('album/_link.phtml', array('album' => $this->album, 'showArtist' => true)); ?>
    </li>
    <li><?php echo $this->partial()->setObjectKey('label')->partial('label/_link.phtml', $this->album->label); ?>
      <?php if (!empty($this->album->catalogNumber)): ?>
         | <?php echo $this->album->catalogNumber ?>
      <?php endif ?></li>
    <li>Wydany <?php echo $this->album->releaseDateNormalized; ?></li>
  </ul>
</li>