<!doctype html> 
<html lang="pl">
<!--  xmlns:og="http://opengraphprotocol.org/schema/" -->
<head>
<?php echo $this->headMeta(); ?>
<meta name="google-site-verification" content="HsOI_FHfSVoTani2UHBr9Jh7G8sXNYfXTUCyg5VDYLY" />
<?php echo $this->headTitle(); ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/s.min.css'); ?>
<?php echo $this->headLink(); ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script><?php $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.tipsy.js') ?>
<?php echo $this->headScript(); ?>
<script src="/js/s.min.js" type="text/javascript" charset="utf-8"></script>
<link href="/favicon.ico?" rel="shortcut icon" type="image/x-icon" />

<link rel="search" type="application/opensearchdescription+xml" title="Hhbd.pl" href="/opensearch.xml">

<!-- <meta http-equiv="cache-control" content="max-age=0, must-revalidate" /> -->

<?php if (!empty($this->og)) { echo $this->og; } ?>
<?php echo $this->partial('common/_googleAnalytics.phtml'); ?>
</head>
<body>
<div id="body">
  <p class="hidden"><a href="#content" title="Pomija nawigację i nagłówek strony">Przejdź do głównej treści strony</a></p>
  <div id="page">
    <div id="header">
      <div id="logo">
<?php if ($this->url() != $this->baseUrl() . '/' ): ?>
        <a href="<?php echo $this->baseUrl(); ?>">
<?php endif ?>
          <div>Przejdź do strony głónwej Hhbd.pl</div>
<?php if ($this->url() != $this->baseUrl() . '/' ): ?>
        </a>
<?php endif ?>
      </div>
<?php echo $this->partial('_nav.phtml') ?>
  </div> <!-- header -->

    <!-- message box -->
    <?php if (isset($this->messageType)) { ?>
    <div id="message" class="<?php echo $this->messageType; ?>">
      <?php echo $this->message; ?>
    </div>
    <?php } ?>

    <!-- <h3><?php echo $this->translate('Main menu') ?></h3> -->

    <?php
      // $partial = array('common/nav.phtml', 'default');
      // $this->navigation()->menu()->setPartial($partial);
      // echo $this->navigation()->menu()->setOnlyActiveBranch(true);
  
      //echo $this->navigation()->menu()->render();
    ?>
    <!-- <h3><?php echo $this->translate('Breadcrumb') ?></h3> -->

    <!-- <div id="breadcrumbs">
      <?php echo $this->navigation()->breadcrumbs()->render(); ?>
    </div> -->

    <div id="content">
    	<?php echo $this->layout()->content; ?>
    </div>

    <div id="footer">
      <ul>
        <li>&copy; 2004-<?php echo date('Y'); ?> Hhbd.pl</li>
        <li><a href="<?php echo $this->url(array(),'contact') ?>">Kontakt</a></li>
        <li><a href="<?php echo $this->url(array(),'about') ?>">O nas</a></li>
        <!-- <li><a href="/blog.html">Blog</a></li> -->
        <!-- <li><a href="/zasady.html">Zasady użytkowania</a></li> -->
        <!-- <li><a href="/mapa-strony.html">Mapa strony</a></li> -->
        <li>realizacja: <a href="http://www.webascrazy.net" target="_blank">www.webascrazy.net</a></li>
      </ul>
      <div id="disclaimer">Hhbd.pl, czyli Hip-Hopowa Baza Danych jest największa encyklopedią polskiego hip-hopu. U nas znajdziesz wszystkie interesujące Cię informacje dotyczące polskich wykonawców, wytwórni i albumów. Mamy informacje o premierach, tekstach, oraz teledyskach. Listę wydanych albumów, biografie i dyskografie raperów i składów. Oprócz tego teksty piosenek, informacje o występach gościnnych, producentach, djach i inne. Jeżeli jesteś zainteresowany współpracą, zapraszamy <a href="/kontakt.html">do kontaktu</a>.</div>
    </div>
  </div>
</div>
</body>
</html>