<div id="main">
  <h1>Lista wytwórni</h1>
  
  <div class="list">
    <table>
      <theader>
        <tr><th>Nazwa</th><th>Ilość wydanych albumów</th><th>Strona internetowa</th></tr>
      </theader>
      <tbody>
        <?php foreach ($this->labels->items as $key => $value): ?>
          <tr>
            <td><?php echo $this->partial('label/_link.phtml', array('label' =>$value)) ?></td>
            <td><?php echo $value->albumCount ?></td>
            <td><?php if (isset($value->website)): ?><?php echo $value->website ?><?php endif ?></td>
          </tr>
        <?php endforeach ?>
      </tbody>
      <caption class="hidden">Lista polskich wytwóri hip-hopowych</caption>
    </table>
  </div>

  
</div>

<div id="additional">
  <div class="box googleads">
    <h3 class="hidden">Google Ads</h3>
    <?php echo $this->partial('common/googleAds/_rectangle.phtml'); ?>
  </div>
</div>