<div class="googleads">
  <h2 class="hidden">Google Ads</h2>
  <?php echo $this->partial('common/googleAds/_rectangle.phtml'); ?>
</div>

<div class="user hidden">
  <h2>Personalizacja</h2>
  <ul>
    <li>W kolekcji: </li>
    <li>W chcęliście: </li>
  </ul>
</div>

<div class="teksty lyrics">
  <h2>Teksty piosenek</h2>
  Sprawdź dostępne na naszej stronie teksty piosenek, wystarczy, że wybierzesz któryś utwór z playlisty.
</div>

<div class="wrzuta chomikuj hidden">
  <h2>Linki</h2>
  <ul>
    <li>Wrzuta.pl</li>
    <li>Chomikuj.pl</li>
  </ul>
</div>
