<form action="<?php echo $this->url(array(), 'userLogin') ?>" method="post">
  <label>E-mail</label>
  <input type="text" name="email" value="" />
  <label>Hasło</label>
  <input type="password" name="password" />
  <?php if ($this->url(array(), 'userLogin') == $this->url()): ?>
    <input type="hidden" name="url" value="/">
  <?php else: ?>
    <input type="hidden" name="url" value="<?php echo $this->url() ?>">
  <?php endif ?>
  
  <input type="submit" value="Zaloguj" />
</form>