<div id="main">
  <h2>Użytkownik <?php echo $this->user->getDisplayName() ?></h2>
  <div id="pane">
    <div class="header">
      <h2>Info</h2>
    </div>
    <p>To odsłona profilu użytkownika <strong><?php echo $this->user->getDisplayName() ?></strong>. Na razie nie ma tutaj dużo ustawień i informacji, jednak pracujemy nad tym i niedługo zaczną się pojawiać nowe opcje.</p>
    <p>W tej chwili po zalogowaniu możesz zostawiać komentarze, ze swoim podpisem oraz uzupełniać swoją kolekcję oraz chcęlistę.</p>
    <p>W najbliższej przyszłości planujemy uruchomić:
      <ul class="list">
        <li>Ocenianie albumów, wykonawców, utworów, newsów i wytwóri.</li>
        <li>Dodawanie sampli do utworów.</li>
        <li>Ustawienia profilu.</li>
      </ul>
    </p>
  </div>
  
  <div class="pane">
    <div class="header">
        <h2>Kolekcja</h2>
    </div>
    <ul>
        <li>lista...</li>
    </ul>
  </div>
  
  <div class="pane">
    <div class="header">
        <h2>Chcęlista</h2>
    </div>
    <ul>
        <li>lista...</li>
    </ul>
  </div>
  
  
</div>

<div id="aside">
  <div class="box googleads">
    <h3 class="hidden">Google Ads</h3>
    <?php echo $this->partial('common/googleAds/_rectangle.phtml'); ?>
  </div>
</div>