<h1><?php echo $this->partial('artist/_link.phtml', array('artist' => $this->album->artist)) ?> - <?php echo $this->album->title ?></h1>

<div id="main">
	<div id="picture">
	  <img src="<?php echo $this->album->cover ?>" alt="Okładka albumu <?php echo $this->album->title ?>" title="<?php echo $this->album->title . ' - ' . $this->album->artist->name ?>" class="image" />
    <!-- <span id="case"></span> -->
	</div>
  	
	<div id="brief">
  	<h2 class="hidden">Informacje podstawowe</h2>
  	
  	<ul id="essential">
      <?php if (!empty($this->album->releaseDate)): ?>
        <li><span>
        <?php if ($this->album->isAnnounced()): ?>
          Planowana data
        <?php else: ?>
          Data 
        <?php endif ?>
        wydania:</span> <?php echo $this->album->releaseDateNormalized ?>
        </li>
      <?php endif ?>
    
      <li><span>Wydawnictwo:</span> 
      <?php if (!empty($this->album->label)): ?>
        <?php echo $this->partial('label/_link.phtml', array('label' => $this->album->label)); ?>
      <?php else: ?>
        brak informacji
      <?php endif ?>
      </li>
      
      <li><span>Studio nagrań:</span> --</li>
    
      <li><span>Numer katalogowy:</span>
        <?php if (!empty($this->album->catalogNumber)): ?>
          <?php echo $this->album->catalogNumber ?>
        <?php else: ?>
          --
        <?php endif ?>
      </li>
    </ul>

    <ul id="details">
      <!-- <li>Dodany: <?php echo $this->album->added ?></li> -->
      <?php if (!empty($this->album->epFor)): ?>
        <li><span>Singiel do:</span> <?php echo $this->partial('album/_link.phtml', array('album' => $this->album->epFor)) ?> </li>
      <?php endif ?>
      <?php if (!empty($this->album->eps->items)): ?>
        <li><span>Poprzedzony singlami:</span>
        <ul class="eps">
          <?php foreach ($this->album->eps->items as $ep): ?>
            <li><?php echo $this->partial('album/_link.phtml', array('album' => $ep)) ?></li>
          <?php endforeach ?>
        </ul>
        </li>
      <?php endif ?>
      <li><span>Czas trwania:</span> <?php if ($this->album->duration == 0): ?>
        --:--
        <?php else: ?>
          <?php echo $this->album->duration ?>
        <?php endif ?>
      </li>
      <li><span>Ocena:</span> <?php echo $this->album->rating ?>/10 (<?php echo $this->album->voteCount ?> głosów)</li>
  	</ul>
  </div> <!-- brief -->
  
  <?php if (!empty($this->album->tracklist->items)): ?>
  <div id="tracklist">
    <h2>Lista utworów</h2> <span class="toggle">(<a href="?hideDetailes=1">Ukryj szczegóły</a>)</span>
    <table>
      <tr class="hidden"><th>Numer</th><th>Wykonawca</th><th>Tytuł</th><th>Czas trwania</th></tr>
      <?php foreach ($this->album->tracklist->items as $song): ?>
        <tr>
          <td><?php echo $song->track ?></td>
          <td class="align">
            <?php foreach ($song->artist->items as $feat): ?>
              <?php echo $this->partial('artist/_link.phtml', array('artist' => $feat)) ?><br />
            <?php endforeach ?>
          </td>
          
          <td>
            <?php echo $this->partial('song/_link.phtml', array('song' => $song)) ?>
            <ul>
            <li class="feat">
              <?php foreach ($song->featuring->items as $feat): ?>
                gościnnie: <?php echo $this->partial('artist/_link.phtml', array('artist' => $feat)) ?> (<?php echo $feat->featType ?>)<br />
              <?php endforeach ?>
            </li>
            <li class="feat">
              <?php foreach ($song->music->items as $feat): ?>
                <?php echo $this->partial('artist/_link.phtml', array('artist' => $feat)) ?> (Muzyka)<br />
              <?php endforeach ?>
            </li>
            <li class="feat">
              <?php foreach ($song->scratch->items as $feat): ?>
                <?php echo $this->partial('artist/_link.phtml', array('artist' => $feat)) ?> (Scratch)<br />
              <?php endforeach ?>
            </li>
          </ul>
          </td>
          <td class="align"><?php echo $song->duration ?></td>
        </tr>
      <?php endforeach ?>
    </table>
  </div>
  <?php endif ?>

  <?php if (!empty($this->album->description)): ?>
  <div id="description">
    <h2>Opis produkcji</h2>
  	<p><?php echo $this->album->description ?></p>
  </div>
  <?php endif ?>

</div> <!-- main -->

<div id="additional"><?php echo $this->partial('album/_additional.phtml') ?></div>