<ul> 
    <li class="active"><a href="http://hhbdevolution.kosiarka/">Strona główna</a></li>
    <li><a href="http://hhbdevolution.kosiarka/top10.html">Top 10</a></li> 
    <li><a href="http://hhbdevolution.kosiarka/albumy.html">Albumy</a></li> 
    <li><a href="http://hhbdevolution.kosiarka/albumy/zapowiedziane.html">Zapowiedziane</a></li>
    <li><a href="http://hhbdevolution.kosiarka/wykonawcy.html">Wykonawcy</a></li> 
    <li><a href="http://hhbdevolution.kosiarka/wytwornie.html">Wytwórnie</a></li> 
</ul>