<div class="box googleads">
  <h3 class="hidden">Google Ads</h3>
  <?php echo $this->partial('common/googleAds/_rectangle.phtml'); ?>
</div>

<div class="box user">
  <h3>Personalizacja</h3>
  <ul>
    <li>Ulubiony: <span class="button">Dodaj do ulubionych</span></li>
  </ul>
</div>

<div class="box stats">
  <h3>Statystyki</h3>
  <ul>
    <li>Popularność: </li>
    <li>Wydanych albumów: </li>
    <li>W tym w projektach: </li>
    <li>Gościnnych występów: </li>
    <li>Muzyka na {} albumach</li>
    <li>Rap na {} albumach</li>
  </ul>
</div>

<div class="box featuring">
  <h3>Występy gościnne</h3>
  <ul>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
  </ul>
</div>

<div class="box music">
  <h3>Muzyka</h3>
  <ol>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
  </ol>
</div>

<div class="box songs">
  <h3>Najpopularniejsze utwory</h3>
  <ul>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
  </ul>
</div>

<div class="box music">
  <h3>Rap</h3>
  <ul>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
    <li>Tytuł (2010, RRX)</li>
  </ul>
</div>

<div class="box teksty lyrics hidden">
  <h3>Teksty piosenek</h3>
  Sprawdź dostępne na naszej stronie teksty piosenek, wystarczy, że wybierzesz któryś utwór z playlisty.
</div>

<div class="box wrzuta chomikuj hidden">
  <h3>Linki</h3>
  <ul>
    <li>Wrzuta.pl</li>
    <li>Chomikuj.pl</li>
  </ul>
</div>
